# Generated by Django 3.2.25 on 2025-12-06 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsalvo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_autoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='colaboradores_confirmados',
            field=models.ManyToManyField(blank=True, related_name='colaboracoes_confirmadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='colaboradores_pendentes',
            field=models.ManyToManyField(blank=True, related_name='convites_recebidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='materiais_curtidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicopesquisa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='convitecolaboracao',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_recebidos_detalhados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='convitecolaboracao',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material'),
        ),
        migrations.AddField(
            model_name='convitecolaboracao',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_enviados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='comentarios_curtidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app.material'),
        ),
    ]
