# Generated by Django 3.2.25 on 2025-11-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_frasedodia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FraseDoDia',
        ),
    ]
