# Generated by Django 3.2.25 on 2025-11-30 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0021_delete_frasedodia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_autoria', to=settings.AUTH_USER_MODEL),
        ),
    ]
